### ISSUE TITLE
Investigate and document Google Trends API

### ISSUE THREAD

**Issue by nieksonneveld** [oscarhibbert/election-predictor#10]

**Comment by oscarhibbert** [comment]
@nieksonneveld I did some initial research, it looks like Google Trends doesn't have an official API.

There is a Python package which can help us, suggested by Chat GPT. When choosing a package like this we should be mindful and get whether it's properly supported (especially if open source). i.e. if something broke with the package we'd be in trouble etc.

Here is Chat GPTs initial take:
https://chatgpt.com/share/e/87775a18-3362-4277-b60c-bc26fa7fb328

**Comment by oscarhibbert** [comment]
Good article here on https://medium.com/nerd-for-tech/5-serp-apis-that-can-beat-google-at-their-own-game-665b86aa822c

And then finally see this documentation for Trends and News API:

https://serpapi.com/local-news
